vocabs = [
    {"V1": "build", "V3": "built", "IPA_V1": "/bɪld/", "IPA_V3": "/bɪlt/", "Meaning": "xây dựng", "IT": "have built a system, have built an app"},
    {"V1": "buy", "V3": "bought", "IPA_V1": "/baɪ/", "IPA_V3": "/bɔːt/", "Meaning": "mua", "IT": "have bought software, have bought a license"},
    {"V1": "catch", "V3": "caught", "IPA_V1": "/kætʃ/", "IPA_V3": "/kɔːt/", "Meaning": "bắt", "IT": "have caught an exception"},
    {"V1": "choose", "V3": "chosen", "IPA_V1": "/tʃuːz/", "IPA_V3": "/ˈtʃəʊzn/", "Meaning": "chọn", "IT": "have chosen an algorithm, have chosen a config"},
    {"V1": "come", "V3": "come", "IPA_V1": "/kʌm/", "IPA_V3": "/kʌm/", "Meaning": "đến", "IT": "a request has come to the server"},
    {"V1": "cost", "V3": "cost", "IPA_V1": "/kɒst/", "IPA_V3": "/kɒst/", "Meaning": "tốn", "IT": "has cost the system resources"},
    {"V1": "cut", "V3": "cut", "IPA_V1": "/kʌt/", "IPA_V3": "/kʌt/", "Meaning": "cắt", "IT": "have cut code, have cut a string"},
    {"V1": "deal", "V3": "dealt", "IPA_V1": "/diːl/", "IPA_V3": "/delt/", "Meaning": "xử lý", "IT": "have dealt with errors"},
    {"V1": "do", "V3": "done", "IPA_V1": "/duː/", "IPA_V3": "/dʌn/", "Meaning": "làm", "IT": "have done tasks, have done a commit"},
    {"V1": "draw", "V3": "drawn", "IPA_V1": "/drɔː/", "IPA_V3": "/drɔːn/", "Meaning": "vẽ", "IT": "have drawn the interface, have drawn diagrams"},
    {"V1": "find", "V3": "found", "IPA_V1": "/faɪnd/", "IPA_V3": "/faʊnd/", "Meaning": "tìm", "IT": "have found bugs, have found elements"},
    {"V1": "get", "V3": "got/gotten", "IPA_V1": "/ɡet/", "IPA_V3": "/ɡɒt/ /ˈɡɒtn/", "Meaning": "lấy", "IT": "have gotten data, have gotten a request"},
    {"V1": "give", "V3": "given", "IPA_V1": "/ɡɪv/", "IPA_V3": "/ˈɡɪvn/", "Meaning": "đưa", "IT": "have given permissions"},
    {"V1": "go", "V3": "gone", "IPA_V1": "/ɡəʊ/", "IPA_V3": "/ɡɒn/", "Meaning": "đi", "IT": "have gone live, have gone to the next step"},
    {"V1": "have", "V3": "had", "IPA_V1": "/hæv/", "IPA_V3": "/hæd/", "Meaning": "có", "IT": "have had access"},
    {"V1": "input", "V3": "input", "IPA_V1": "/ˈɪnpʊt/", "IPA_V3": "/ˈɪnpʊt/", "Meaning": "nhập", "IT": "have input data"},
    {"V1": "keep", "V3": "kept", "IPA_V1": "/kiːp/", "IPA_V3": "/kept/", "Meaning": "giữ", "IT": "have kept the session alive"},
    {"V1": "know", "V3": "known", "IPA_V1": "/nəʊ/", "IPA_V3": "/nəʊn/", "Meaning": "biết", "IT": "have known the system well"},
    {"V1": "leave", "V3": "left", "IPA_V1": "/liːv/", "IPA_V3": "/left/", "Meaning": "rời", "IT": "a user has left the project"},
    {"V1": "let", "V3": "let", "IPA_V1": "/let/", "IPA_V3": "/let/", "Meaning": "cho phép", "IT": "have let the user log in"},
    {"V1": "make", "V3": "made", "IPA_V1": "/meɪk/", "IPA_V3": "/meɪd/", "Meaning": "tạo", "IT": "have made an API, have made a decision"},
    {"V1": "meet", "V3": "met", "IPA_V1": "/miːt/", "IPA_V3": "/met/", "Meaning": "đáp ứng, gặp", "IT": "have met all requirements"},
    {"V1": "output", "V3": "output", "IPA_V1": "/ˈaʊtpʊt/", "IPA_V3": "/ˈaʊtpʊt/", "Meaning": "xuất ra", "IT": "have output the data"},
    {"V1": "put", "V3": "put", "IPA_V1": "/pʊt/", "IPA_V3": "/pʊt/", "Meaning": "đặt vào", "IT": "have put data into the database"},
    {"V1": "read", "V3": "read", "IPA_V1": "/riːd/", "IPA_V3": "/red/", "Meaning": "đọc", "IT": "have read the file, have read the config"},
    {"V1": "rewrite", "V3": "rewritten", "IPA_V1": "/ˌriːˈraɪt/", "IPA_V3": "/rɪˈrɪtn/", "Meaning": "viết lại", "IT": "have rewritten the code"},
    {"V1": "run", "V3": "run", "IPA_V1": "/rʌn/", "IPA_V3": "/rʌn/", "Meaning": "chạy", "IT": "have run the app, have run the server"},
    {"V1": "say", "V3": "said", "IPA_V1": "/seɪ/", "IPA_V3": "/sed/", "Meaning": "nói", "IT": "have said it in the log"},
    {"V1": "see", "V3": "seen", "IPA_V1": "/siː/", "IPA_V3": "/siːn/", "Meaning": "thấy", "IT": "have seen the output, have seen the result"},
    {"V1": "send", "V3": "sent", "IPA_V1": "/send/", "IPA_V3": "/sent/", "Meaning": "gửi", "IT": "have sent a request, have sent an email"},
    {"V1": "set", "V3": "set", "IPA_V1": "/set/", "IPA_V3": "/set/", "Meaning": "thiết lập", "IT": "have set variables, have set the IP"},
    {"V1": "show", "V3": "shown", "IPA_V1": "/ʃəʊ/", "IPA_V3": "/ʃəʊn/", "Meaning": "hiển thị", "IT": "have shown a message, have shown the UI"},
    {"V1": "shut", "V3": "shut", "IPA_V1": "/ʃʌt/", "IPA_V3": "/ʃʌt/", "Meaning": "tắt", "IT": "have shut down the server"},
    {"V1": "take", "V3": "taken", "IPA_V1": "/teɪk/", "IPA_V3": "/ˈteɪkən/", "Meaning": "lấy", "IT": "have taken input, have taken a backup"},
    {"V1": "think", "V3": "thought", "IPA_V1": "/θɪŋk/", "IPA_V3": "/θɔːt/", "Meaning": "nghĩ", "IT": "have thought about the logic"},
    {"V1": "throw", "V3": "thrown", "IPA_V1": "/θrəʊ/", "IPA_V3": "/θrəʊn/", "Meaning": "ném", "IT": "have thrown an error"},
    {"V1": "understand", "V3": "understood", "IPA_V1": "/ˌʌndəˈstænd/", "IPA_V3": "/ˌʌndəˈstʊd/", "Meaning": "hiểu", "IT": "have understood the code"},
    {"V1": "update", "V3": "updated", "IPA_V1": "/ʌpˈdeɪt/", "IPA_V3": "/ʌpˈdeɪtɪd/", "Meaning": "cập nhật", "IT": "have updated the system"},
    {"V1": "wear", "V3": "worn", "IPA_V1": "/weə(r)/", "IPA_V3": "/wɔːn/", "Meaning": "mang (bảo mật)", "IT": "have worn the security token"},
    {"V1": "write", "V3": "written", "IPA_V1": "/raɪt/", "IPA_V3": "/ˈrɪtn/", "Meaning": "viết", "IT": "have written code, have written a file"},
    {"V1": "begin", "V3": "begun", "IPA_V1": "/bɪˈɡɪn/", "IPA_V3": "/bɪˈɡʌn/", "Meaning": "bắt đầu", "IT": "have begun the transaction"},
    {"V1": "break", "V3": "broken", "IPA_V1": "/breɪk/", "IPA_V3": "/ˈbrəʊkən/", "Meaning": "phá vỡ", "IT": "have broken the loop, have broken a link"},
    {"V1": "broadcast", "V3": "broadcast", "IPA_V1": "/ˈbrɔːdkɑːst/", "IPA_V3": "/ˈbrɔːdkɑːst/", "Meaning": "phát sóng", "IT": "have broadcast a message, have broadcast to the network"},
    {"V1": "freeze", "V3": "frozen", "IPA_V1": "/friːz/", "IPA_V3": "/ˈfrəʊzn/", "Meaning": "đóng băng", "IT": "have frozen the UI"},
    {"V1": "hide", "V3": "hidden", "IPA_V1": "/haɪd/", "IPA_V3": "/ˈhɪdn/", "Meaning": "ẩn", "IT": "have hidden the password, have hidden a file"},
    {"V1": "lose", "V3": "lost", "IPA_V1": "/luːz/", "IPA_V3": "/lɒst/", "Meaning": "mất", "IT": "have lost the connection, have lost data"},
    {"V1": "speak", "V3": "spoken", "IPA_V1": "/spiːk/", "IPA_V3": "/ˈspəʊkən/", "Meaning": "nói", "IT": "have spoken via voice command"},
    {"V1": "wake", "V3": "woken", "IPA_V1": "/weɪk/", "IPA_V3": "/ˈwəʊkən/", "Meaning": "đánh thức", "IT": "have woken the system using Wake-on-LAN"},
    {"V1": "drink", "V3": "drunk",       "IPA_V1": "/drɪŋk/",     "IPA_V3": "/drʌŋk/",     "Meaning": "uống",        "IT": "have drunk the coffee (dev break)"},
    {"V1": "drive", "V3": "driven",     "IPA_V1": "/draɪv/",     "IPA_V3": "/ˈdrɪvn/",    "Meaning": "lái",         "IT": "have driven deployment scripts"},
    {"V1": "eat", "V3": "eaten",        "IPA_V1": "/iːt/",       "IPA_V3": "/ˈiːtn/",     "Meaning": "ăn",          "IT": "have eaten CPU cycles"},
    {"V1": "fall", "V3": "fallen",      "IPA_V1": "/fɔːl/",      "IPA_V3": "/ˈfɔːlən/",    "Meaning": "rơi",        "IT": "have fallen into an infinite loop"},
    {"V1": "feed", "V3": "fed",         "IPA_V1": "/fiːd/",      "IPA_V3": "/fed/",        "Meaning": "cho ăn",      "IT": "have fed data into the model"},
    {"V1": "feel", "V3": "felt",        "IPA_V1": "/fiːl/",      "IPA_V3": "/felt/",       "Meaning": "cảm thấy",    "IT": "have felt high system load"},
    {"V1": "fly", "V3": "flown",        "IPA_V1": "/flaɪ/",      "IPA_V3": "/fləʊn/",      "Meaning": "bay",         "IT": "have flown through the tests"},
    {"V1": "forget", "V3": "forgotten", "IPA_V1": "/fəˈɡet/",    "IPA_V3": "/fəˈɡɒtn/",    "Meaning": "quên",        "IT": "have forgotten to commit changes"},
    {"V1": "get up", "V3": "got up",    "IPA_V1": "/ɡet ʌp/",    "IPA_V3": "/ɡɒt ʌp/",     "Meaning": "thức dậy",     "IT": "have got up early to fix the bug"},
    {"V1": "grow", "V3": "grown",       "IPA_V1": "/ɡrəʊ/",      "IPA_V3": "/ɡrəʊn/",      "Meaning": "phát triển",  "IT": "have grown the user base"},
    {"V1": "hear", "V3": "heard",       "IPA_V1": "/hɪər/",      "IPA_V3": "/hɜːd/",       "Meaning": "nghe",        "IT": "have heard feedback from users"},
    {"V1": "hide", "V3": "hidden",      "IPA_V1": "/haɪd/",      "IPA_V3": "/ˈhɪdn/",      "Meaning": "ẩn",          "IT": "have hidden the password field"},
    {"V1": "hit", "V3": "hit",          "IPA_V1": "/hɪt/",       "IPA_V3": "/hɪt/",        "Meaning": "đánh trúng",   "IT": "have hit the rate limit"},
    {"V1": "hold", "V3": "held",        "IPA_V1": "/həʊld/",     "IPA_V3": "/held/",       "Meaning": "giữ",         "IT": "have held the connection open"},
    {"V1": "hurt", "V3": "hurt",        "IPA_V1": "/hɜːt/",      "IPA_V3": "/hɜːt/",        "Meaning": "làm đau",       "IT": "have hurt performance"},
    {"V1": "keep", "V3": "kept",        "IPA_V1": "/kiːp/",      "IPA_V3": "/kept/",       "Meaning": "giữ",         "IT": "have kept the session alive"},
    {"V1": "knit", "V3": "knitted/knit","IPA_V1": "/nɪt/",     "IPA_V3": "/ˈnɪtɪd/ /nɪt/","Meaning": "đan",         "IT": "have knit the modules together"},
    {"V1": "know", "V3": "known",       "IPA_V1": "/nəʊ/",       "IPA_V3": "/nəʊn/",       "Meaning": "biết",        "IT": "have known the system"},
    {"V1": "lay", "V3": "laid",         "IPA_V1": "/leɪ/",       "IPA_V3": "/leɪd/",       "Meaning": "đặt xuống",    "IT": "have laid out the architecture"},
    {"V1": "lead", "V3": "led",         "IPA_V1": "/liːd/",      "IPA_V3": "/led/",        "Meaning": "dẫn dắt",     "IT": "have led the project team"},
    {"V1": "lend", "V3": "lent",        "IPA_V1": "/lend/",      "IPA_V3": "/lent/",       "Meaning": "cho mượn",   "IT": "have lent credentials"},
    {"V1": "let", "V3": "let",          "IPA_V1": "/let/",       "IPA_V3": "/let/",        "Meaning": "cho phép",     "IT": "have let the user log in"},
    {"V1": "light", "V3": "lit/lighted","IPA_V1": "/laɪt/",    "IPA_V3": "/lɪt/ /ˈlaɪtɪd/","Meaning": "đốt sáng",  "IT": "have lit up the dashboard"},
    {"V1": "lose", "V3": "lost",        "IPA_V1": "/luːz/",      "IPA_V3": "/lɒst/",       "Meaning": "mất",         "IT": "have lost the connection"},
    {"V1": "make", "V3": "made",        "IPA_V1": "/meɪk/",      "IPA_V3": "/meɪd/",        "Meaning": "tạo",         "IT": "have made an API"},
    {"V1": "mean", "V3": "meant",       "IPA_V1": "/miːn/",      "IPA_V3": "/ment/",       "Meaning": "có nghĩa",     "IT": "have meant to commit changes"},
    {"V1": "meet", "V3": "met",         "IPA_V1": "/miːt/",      "IPA_V3": "/met/",        "Meaning": "gặp, đáp ứng","IT": "have met all requirements"},
    {"V1": "pay", "V3": "paid",         "IPA_V1": "/peɪ/",       "IPA_V3": "/peɪd/",        "Meaning": "trả",         "IT": "have paid the subscription"},
    {"V1": "put", "V3": "put",          "IPA_V1": "/pʊt/",       "IPA_V3": "/pʊt/",        "Meaning": "đặt",         "IT": "have put data into DB"},
    {"V1": "read", "V3": "read",        "IPA_V1": "/riːd/",      "IPA_V3": "/red/",        "Meaning": "đọc",         "IT": "have read the config"},
    {"V1": "ride", "V3": "ridden",      "IPA_V1": "/raɪd/",      "IPA_V3": "/ˈrɪdn/",       "Meaning": "đi (xe)",     "IT": "have ridden the wave of adoption"},
    {"V1": "ring", "V3": "rung",        "IPA_V1": "/rɪŋ/",       "IPA_V3": "/rʌŋ/",        "Meaning": "đổ chuông",    "IT": "have rung the alert"},
    {"V1": "rise", "V3": "risen",       "IPA_V1": "/raɪz/",      "IPA_V3": "/ˈrɪzn/",       "Meaning": "tăng lên",     "IT": "have risen to the challenge"},
    {"V1": "run", "V3": "run",          "IPA_V1": "/rʌn/",       "IPA_V3": "/rʌn/",        "Meaning": "chạy",         "IT": "have run tests"},
    {"V1": "say", "V3": "said",         "IPA_V1": "/seɪ/",       "IPA_V3": "/sed/",        "Meaning": "nói",         "IT": "have said it in the logs"},
    {"V1": "see", "V3": "seen",         "IPA_V1": "/siː/",       "IPA_V3": "/siːn/",        "Meaning": "thấy",        "IT": "have seen the output"},
    {"V1": "sell", "V3": "sold",        "IPA_V1": "/sel/",       "IPA_V3": "/səʊld/",      "Meaning": "bán",         "IT": "have sold the plugin"},
    {"V1": "send", "V3": "sent",        "IPA_V1": "/send/",      "IPA_V3": "/sent/",       "Meaning": "gửi",         "IT": "have sent the request"},
    {"V1": "set", "V3": "set",          "IPA_V1": "/set/",       "IPA_V3": "/set/",        "Meaning": "đặt, thiết lập","IT": "have set variables"},
    {"V1": "shake", "V3": "shaken",     "IPA_V1": "/ʃeɪk/",      "IPA_V3": "/ˈʃeɪkən/",     "Meaning": "lắc",         "IT": "have shaken up the system config"},
    {"V1": "shine", "V3": "shone",      "IPA_V1": "/ʃaɪn/",      "IPA_V3": "/ʃɒn/",        "Meaning": "tỏa sáng",    "IT": "have shone in performance tests"},
    {"V1": "shoot", "V3": "shot",       "IPA_V1": "/ʃuːt/",      "IPA_V3": "/ʃɒt/",         "Meaning": "bắn",         "IT": "have shot the signal"},
    {"V1": "show", "V3": "shown",       "IPA_V1": "/ʃəʊ/",       "IPA_V3": "/ʃəʊn/",        "Meaning": "hiển thị",     "IT": "have shown the UI"},
    {"V1": "shut", "V3": "shut",        "IPA_V1": "/ʃʌt/",       "IPA_V3": "/ʃʌt/",        "Meaning": "đóng, đóng",   "IT": "have shut down the server"},
    {"V1": "sing", "V3": "sung",        "IPA_V1": "/sɪŋ/",       "IPA_V3": "/sʌŋ/",        "Meaning": "hát",         "IT": "have sung the version number aloud"},
    {"V1": "sit", "V3": "sat",          "IPA_V1": "/sɪt/",       "IPA_V3": "/sæt/",        "Meaning": "ngồi",        "IT": "have sat through the meeting"},
    {"V1": "sleep", "V3": "slept",      "IPA_V1": "/sliːp/",     "IPA_V3": "/slept/",       "Meaning": "ngủ",         "IT": "have slept mode activated"},
    {"V1": "speak", "V3": "spoken",     "IPA_V1": "/spiːk/",     "IPA_V3": "/ˈspəʊkən/",    "Meaning": "nói",         "IT": "have spoken via voice interface"},
    {"V1": "spend", "V3": "spent",      "IPA_V1": "/spend/",     "IPA_V3": "/spent/",      "Meaning": "dành (thời gian)", "IT": "have spent hours debugging"},
    {"V1": "stand", "V3": "stood",      "IPA_V1": "/stænd/",     "IPA_V3": "/stud/",        "Meaning": "đứng",        "IT": "have stood by the deployment"},
    {"V1": "steal", "V3": "stolen",     "IPA_V1": "/stiːl/",     "IPA_V3": "/ˈstəʊlən/",    "Meaning": "ăn cắp",      "IT": "have stolen the show with performance"},
    {"V1": "swim", "V3": "swum",        "IPA_V1": "/swɪm/",      "IPA_V3": "/swʌm/",        "Meaning": "bơi",         "IT": "have swum against the tide of errors"},
    {"V1": "take", "V3": "taken",       "IPA_V1": "/teɪk/",      "IPA_V3": "/ˈteɪkən/",     "Meaning": "lấy",         "IT": "have taken input from URL"},
    {"V1": "teach", "V3": "taught",     "IPA_V1": "/tiːtʃ/",     "IPA_V3": "/tɔːt/",        "Meaning": "dạy",         "IT": "have taught the model"},
    {"V1": "tear", "V3": "torn",        "IPA_V1": "/teə(r)/",    "IPA_V3": "/tɔːn/",        "Meaning": "rách",        "IT": "have torn down the old UI"},
    {"V1": "think", "V3": "thought",    "IPA_V1": "/θɪŋk/",     "IPA_V3": "/θɔːt/",        "Meaning": "nghĩ",        "IT": "have thought through the logic"},
    {"V1": "throw", "V3": "thrown",     "IPA_V1": "/θrəʊ/",      "IPA_V3": "/θrəʊn/",       "Meaning": "ném",         "IT": "have thrown an error"},
    {"V1": "understand", "V3": "understood","IPA_V1":"/ˌʌndəˈstænd/","IPA_V3":"/ˌʌndəˈstʊd/","Meaning":"hiểu",      "IT":"have understood the code"},
    {"V1": "wake", "V3": "woken",       "IPA_V1": "/weɪk/",      "IPA_V3": "/ˈwəʊkən/",     "Meaning": "đánh thức",    "IT": "have woken the system using Wake-on-LAN"},
    {"V1": "bet", "V3": "bet", "IPA_V1": "/bet/", "IPA_V3": "/bet/", "Meaning": "đánh cược", "IT": "have bet on the release date"},
    {"V1": "bind", "V3": "bound", "IPA_V1": "/baɪnd/", "IPA_V3": "/baʊnd/", "Meaning": "ràng buộc", "IT": "have bound the function to the event"},
    {"V1": "bleed", "V3": "bled", "IPA_V1": "/bliːd/", "IPA_V3": "/bled/", "Meaning": "chảy máu", "IT": "have bled CPU power"},
    {"V1": "breed", "V3": "bred", "IPA_V1": "/briːd/", "IPA_V3": "/bred/", "Meaning": "nuôi, sinh sản", "IT": "have bred new threads"},
    {"V1": "cling", "V3": "clung", "IPA_V1": "/klɪŋ/", "IPA_V3": "/klʌŋ/", "Meaning": "bám lấy", "IT": "have clung to the old API"},
    {"V1": "cost", "V3": "cost", "IPA_V1": "/kɒst/", "IPA_V3": "/kɒst/", "Meaning": "tốn", "IT": "have cost the system resources"},
    {"V1": "crawl", "V3": "crept", "IPA_V1": "/krɔːl/", "IPA_V3": "/krɛpt/", "Meaning": "bò", "IT": "have crept through logs"},
    {"V1": "deal", "V3": "dealt", "IPA_V1": "/diːl/", "IPA_V3": "/delt/", "Meaning": "xử lý", "IT": "have dealt with concurrency issues"},
    {"V1": "dig", "V3": "dug", "IPA_V1": "/dɪg/", "IPA_V3": "/dʌg/", "Meaning": "đào", "IT": "have dug into the database"},
    {"V1": "fit", "V3": "fit", "IPA_V1": "/fɪt/", "IPA_V3": "/fɪt/", "Meaning": "vừa", "IT": "have fit the model to data"},
    {"V1": "kneel", "V3": "knelt", "IPA_V1": "/niːl/", "IPA_V3": "/nɛlt/", "Meaning": "quỳ", "IT": "have knelt the process for priority"},
    {"V1": "lean", "V3": "leant/leaned", "IPA_V1": "/liːn/", "IPA_V3": "/lɛnt/ /liːnd/", "Meaning": "Dựa", "IT": "I leant on my teammates when the project got overwhelming."},
    {"V1": "leap", "V3": "leapt/leaped", "IPA_V1": "/liːp/", "IPA_V3": "/lɛpt/ /liːpt/", "Meaning": "nhảy vọt", "IT": "have leaped over the errors"},
    {"V1": "lend", "V3": "lent", "IPA_V1": "/lɛnd/", "IPA_V3": "/lɛnt/", "Meaning": "cho vay", "IT": "have lent temporary tokens"},
    {"V1": "let", "V3": "let", "IPA_V1": "/let/", "IPA_V3": "/let/", "Meaning": "cho phép", "IT": "have let user use feature"},
    {"V1": "light", "V3": "lit/lighted", "IPA_V1": "/laɪt/", "IPA_V3": "/lɪt/ /ˈlaɪtɪd/", "Meaning": "châm sáng", "IT": "have lit up logs"},
    {"V1": "lose", "V3": "lost", "IPA_V1": "/luːz/", "IPA_V3": "/lɒst/", "Meaning": "mất", "IT": "have lost session data"},
    {"V1": "misread", "V3": "misread", "IPA_V1": "/ˌmɪsˈriːd/", "IPA_V3": "/ˌmɪsˈred/", "Meaning": "đọc nhầm", "IT": "have misread config"},
    {"V1": "mistake", "V3": "mistaken", "IPA_V1": "/mɪˈsteɪk/", "IPA_V3": "/mɪˈsteɪkən/", "Meaning": "nhầm", "IT": "have mistaken the API endpoints"},
    {"V1": "overcome", "V3": "overcome", "IPA_V1": "/ˌəʊvəˈkʌm/", "IPA_V3": "/ˌəʊvəˈkʌm/", "Meaning": "vượt qua", "IT": "have overcome network issues"},
    {"V1": "overwrite", "V3": "overwritten", "IPA_V1": "/ˌəʊvəˈraɪt/", "IPA_V3": "/ˌəʊvəˈrɪtn/", "Meaning": "ghi đè", "IT": "have overwritten the file"},
    {"V1": "partake", "V3": "partaken", "IPA_V1": "/pɑːˈteɪk/", "IPA_V3": "/pɑːˈteɪkən/", "Meaning": "tham gia", "IT": "have partaken in code review"},
    {"V1": "prove", "V3": "proven/proved", "IPA_V1": "/pruːv/", "IPA_V3": "/ˈpruːvn/ /pruːvd/", "Meaning": "chứng minh", "IT": "have proven the algorithm"},
    {"V1": "quit", "V3": "quit", "IPA_V1": "/kwɪt/", "IPA_V3": "/kwɪt/", "Meaning": "thoát", "IT": "have quit the process"},
    {"V1": "read", "V3": "read", "IPA_V1": "/riːd/", "IPA_V3": "/red/", "Meaning": "đọc", "IT": "have read the response"},
    {"V1": "rebuild", "V3": "rebuilt", "IPA_V1": "/ˌriːˈbɪld/", "IPA_V3": "/riːˈbɪlt/", "Meaning": "xây lại", "IT": "have rebuilt the index"},
    {"V1": "redo", "V3": "redone", "IPA_V1": "/ˌriːˈduː/", "IPA_V3": "/riːˈdʌn/", "Meaning": "làm lại", "IT": "have redone the rollout"},
    {"V1": "relay", "V3": "relayed", "IPA_V1": "/rɪˈleɪ/", "IPA_V3": "/rɪˈleɪd/", "Meaning": "chuyển tiếp", "IT": "have relayed the message"},
    {"V1": "remake", "V3": "remade", "IPA_V1": "/ˌriːˈmeɪk/", "IPA_V3": "/riːˈmeɪd/", "Meaning": "làm lại", "IT": "have remade the interface"},
    {"V1": "rerun", "V3": "rerun", "IPA_V1": "/ˌriːˈrʌn/", "IPA_V3": "/ˌriːˈrʌn/", "Meaning": "chạy lại", "IT": "have rerun the tests"},
    {"V1": "rid", "V3": "rid", "IPA_V1": "/rɪd/", "IPA_V3": "/rɪd/", "Meaning": "giải thoát", "IT": "have rid the code of bugs"},
    {"V1": "ring", "V3": "rung", "IPA_V1": "/rɪŋ/", "IPA_V3": "/rʌŋ/", "Meaning": "đổ chuông", "IT": "have rung the alert"},
    {"V1": "rise", "V3": "risen", "IPA_V1": "/raɪz/", "IPA_V3": "/ˈrɪzn/", "Meaning": "tăng lên", "IT": "have risen server load"},
    {"V1": "seek", "V3": "sought", "IPA_V1": "/siːk/", "IPA_V3": "/sɔːt/", "Meaning": "tìm kiếm", "IT": "have sought for a match in logs"},
    {"V1": "sell", "V3": "sold", "IPA_V1": "/sel/", "IPA_V3": "/səʊld/", "Meaning": "bán", "IT": "have sold the plugin"},
    {"V1": "send", "V3": "sent", "IPA_V1": "/send/", "IPA_V3": "/sent/", "Meaning": "gửi", "IT": "have sent the data packet"},
    {"V1": "set", "V3": "set", "IPA_V1": "/set/", "IPA_V3": "/set/", "Meaning": "thiết lập", "IT": "have set environment variables"},
    {"V1": "shed", "V3": "shed", "IPA_V1": "/ʃed/", "IPA_V3": "/ʃed/", "Meaning": "bỏ, rơi", "IT": "have shed unnecessary code"},
    {"V1": "shine", "V3": "shone", "IPA_V1": "/ʃaɪn/", "IPA_V3": "/ʃɒn/", "Meaning": "tỏa sáng", "IT": "have shone in performance tests"},
    {"V1": "shoot", "V3": "shot", "IPA_V1": "/ʃuːt/", "IPA_V3": "/ʃɒt/", "Meaning": "bắn", "IT": "have shot the signal"},
    {"V1": "shut", "V3": "shut", "IPA_V1": "/ʃʌt/", "IPA_V3": "/ʃʌt/", "Meaning": "đóng", "IT": "have shut down the server"},
    {"V1": "sink", "V3": "sunk", "IPA_V1": "/sɪŋk/", "IPA_V3": "/sʌŋk/", "Meaning": "chìm", "IT": "have sunk due to errors"},
    {"V1": "sit", "V3": "sat", "IPA_V1": "/sɪt/", "IPA_V3": "/sæt/", "Meaning": "ngồi", "IT": "have sat through the debug session"},
    {"V1": "sleep", "V3": "slept", "IPA_V1": "/sliːp/", "IPA_V3": "/slept/", "Meaning": "ngủ", "IT": "have slept mode activated"},
    {"V1": "slide", "V3": "slid", "IPA_V1": "/slaɪd/", "IPA_V3": "/slɪd/", "Meaning": "trượt", "IT": "have slid window panes"},
    {"V1": "sling", "V3": "slung", "IPA_V1": "/slɪŋ/", "IPA_V3": "/slʌŋ/", "Meaning": "ném", "IT": "have slung exceptions"},
    {"V1": "slide", "V3": "slid", "IPA_V1": "/slaɪd/", "IPA_V3": "/slɪd/", "Meaning": "trượt", "IT": "have slid the UI panel"},
]

used_vocabs = []